name: ModernDatastores
version: '${project.version}'
main: dev.betrix.moderndatastores.ModernDatastores
api-version: 1.19
authors: [ Betrix ]
description: A simple solution to handling persistent data storage in your Minecraft server.
softdepend:
  - PlaceholderAPI
commands:
  moderndatastores:
    description: Utility command for interacting with ModernDatastores
    aliases:
      - md
    permission: moderndatastores.command